### ISSUE TITLE
复现请教

### ISSUE THREAD

**Issue by chenyanqi-C** [Lieberk/Cutpaste#1]
您好，我最近也看了这篇论文，想请问一下您上传的代码已经成功复现了论文的结果了么？如果方便的话可以看一下结果嘛？

**Comment by Lieberk** [comment]
你好，上传的代码都是成功复现的，具体结果可以看https://aistudio.baidu.com/aistudio/projectdetail/4460691，有问题欢迎随时讨论。


| |
陈立志
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月5日 09:56 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [Lieberk/Paddle-Cutpaste] 复现请教 (Issue #1) |

您好，我最近也看了这篇论文，想请问一下您上传的代码已经成功复现了论文的结果了么？如果方便的话可以看一下结果嘛？

**Comment by chenyanqi-C** [comment]
好的，十分感谢。我还想请问一下有异常的定位结果图嘛，我在您上传的结果中没有找到

**Comment by Lieberk** [comment]
异常定位的结果图暂且还没有复现，急需要的话，可以在项目基础上根据自己的需要继续完善。
| |
陈立志
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月5日 10:23 |
| 收件人 | ***@***.***> |
| 抄送人 | Lizhi ***@***.***> ,
***@***.***> |
| 主题 | Re: [Lieberk/Paddle-Cutpaste] 复现请教 (Issue #1) |

好的，十分感谢。我还想请问一下有异常的定位结果图嘛，我在您上传的结果中没有找到

**Comment by chenyanqi-C** [comment]
好的，我了解了，十分感谢您啦
